name: 'Test Reporter'

on:
  workflow_run:
    workflows: ['Unit Test']
    types:
      - completed
jobs:
  Report:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    - name: Download workflow artifact
      uses: dawidd6/action-download-artifact@v2.11.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: peek_icons.yml
        run_id: ${{ github.event.workflow_run.id }}

    - name: Read the pr_num file
      id: pr_num_reader
      uses: juliangruber/read-file-action@v1.0.0
      with:
        path: ./pr_num/pr_num.txt
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: Reporter
        path: '*.xml'
        reporter: java-junit
        fail-on-error: false
        override-pr: ${{ steps.pr_num_reader.outputs.content }}
